FROM node:alpine

WORKDIR 'app/'

COPY package.json .
RUN npm install

#COPY --chown=node:node package.json .
#RUN npm install

#COPY --chown=node:node . .
#USER node

COPY . .

CMD ["npm", "run", "start"]